services:
  #redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - crawler-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  crawler:
    image: ghcr.io/ghostbyte-dev/fedisea-crawler:latest
    container_name: rust-crawler
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - crawler-network
      - fedisea-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
volumes:
  redis-data:
    driver: local
  postgres_data:

networks:
  crawler-network:
    driver: bridge
  fedisea-network:
    external: true