services:
  #redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - crawler-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  crawler:
    image: ghcr.io/ghostbyte-dev/fedisea-crawler:latest
    container_name: rust-crawler
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - crawler-network
      - fedisea-network
    volumes:
      - geoipupdate_data:/usr/share/GeoIP:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    env_file: .env
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=72
    networks:
      - crawler-network
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'

volumes:
  redis-data:
    driver: local
  geoipupdate_data:
    driver: local

networks:
  crawler-network:
    driver: bridge
  fedisea-network:
    external: true